SELECT B.PRODUCT_CODE, SUM(A.SALES_AMOUNT * B.PRICE) AS SALES_AMOUNT
FROM OFFLINE_SALE A
LEFT JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_CODE
ORDER BY SALES_AMOUNT DESC, B.PRODUCT_CODE ASC
