SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A 
JOIN PATIENT B ON B.PT_NO = A.PT_NO
JOIN DOCTOR C ON C.DR_ID = A.MDDR_ID
WHERE A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '2022-04-13%'
ORDER BY UNIX_TIMESTAMP(A.APNT_YMD) ASC