-- 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
LEFT JOIN REST_REVIEW RR ON RR.REST_ID = RI.REST_ID
WHERE SUBSTR(ADDRESS, 1, 2) = '서울' AND RR.REVIEW_SCORE IS NOT NULL
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC